CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.short_urls
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url    TEXT NOT NULL,
    short_code      TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_short_link_id PRIMARY KEY(id)
);
